// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZDk9iI-e4Y_hScMh4-sevpsGRcv2sf8w',
    appId: '1:131525598595:android:2b304ceecc51eb24b4aab6',
    messagingSenderId: '131525598595',
    projectId: 'photo-tracker-fa162',
    storageBucket: 'photo-tracker-fa162.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDlLGeD4BxQ-xvc5kpL81fbk3FPSuqsZwE',
    appId: '1:131525598595:ios:bb105c91e4d384f3b4aab6',
    messagingSenderId: '131525598595',
    projectId: 'photo-tracker-fa162',
    storageBucket: 'photo-tracker-fa162.appspot.com',
    androidClientId: '131525598595-c8emv5u80tch6ho1m8v3cfs6mlt5scr7.apps.googleusercontent.com',
    iosClientId: '131525598595-sfijrrls7iaih69lg811dp2an9ujgi77.apps.googleusercontent.com',
    iosBundleId: 'com.example.photoTracker',
  );
}
